[build]
publish = "public/"
command = """
pip3 install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install &&
yarn install &&
yarn run build &&
poetry run python speaker-pack-hax.py &&
mkdir -p data/Session &&
poetry run python schedule-sync.py &&
poetry run statik &&
cp _redirects public/
"""